=== fran150/clementina-sdk/specs/schema/background.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://clementina.dev/schema/background.schema.json",
  "title": "Clementina background",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "version",
    "id",
    "name",
    "width",
    "height",
    "tilesetId",
    "altTilesetId",
    "cells"
  ],
  "properties": {
    "format": {
      "const": "clementina-background"
    },
    "version": {
      "const": 1
    },
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
    },
    "name": {
      "type": "string",
      "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,47}$"
    },
    "width": {
      "type": "integer",
      "minimum": 1,
      "maximum": 1024
    },
    "height": {
      "type": "integer",
      "minimum": 1,
      "maximum": 1024
    },
    "tilesetId": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
    },
    "altTilesetId": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
    },
    "cells": {
      "type": "array",
      "minItems": 1,
      "maxItems": 200000,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "tile",
          "paletteBank",
          "flipX",
          "flipY",
          "priority",
          "chrAlt"
        ],
        "properties": {
          "tile": {
            "type": "integer",
            "minimum": 0,
            "maximum": 255
          },
          "paletteBank": {
            "type": "integer",
            "minimum": 0,
            "maximum": 15
          },
          "flipX": {
            "type": "boolean"
          },
          "flipY": {
            "type": "boolean"
          },
          "priority": {
            "type": "boolean"
          },
          "chrAlt": {
            "type": "boolean"
          }
        }
      }
    }
  }
}

=== fran150/clementina-sdk/examples/runtime-demo/assets/backgrounds/0.json
{"format": "clementina-background", "version": 1, "id": "background:level1", "name": "Level1", "width": 40, "height": 25, "tilesetId": "tileset:player", "altTilesetId": "tileset:player", "cells": [{"tile": 0, "paletteBank": 0, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 1, "paletteBank": 1, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 2, "paletteBank": 2, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 3, "paletteBank": 3, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 4, "paletteBank": 4, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 5, "paletteBank": 5, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 6, "paletteBank": 6, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 7, "paletteBank": 7, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 8, "paletteBank": 8, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 9, "paletteBank": 9, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 10, "paletteBank": 10, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 11, "paletteBank": 11, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 12, "paletteBank": 12, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 13, "paletteBank": 13, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 14, "paletteBank": 14, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 15, "paletteBank": 15, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 16, "paletteBank": 0, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 17, "paletteBank": 1, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 18, "paletteBank": 2, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 19, "paletteBank": 3, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 20, "paletteBank": 4, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 21, "paletteBank": 5, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 22, "paletteBank": 6, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 23, "paletteBank": 7, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 24, "paletteBank": 8, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 25, "paletteBank": 9, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 26, "paletteBank": 10, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 27, "paletteBank": 11, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 28, "paletteBank": 12, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 29, "paletteBank": 13, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 30, "paletteBank": 14, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 31, "paletteBank": 15, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 32, "paletteBank": 0, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 33, "paletteBank": 1, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 34, "paletteBank": 2, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 35, "paletteBank": 3, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 36, "paletteBank": 4, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 37, "paletteBank": 5, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 38, "paletteBank": 6, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 39, "paletteBank": 7, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 40, "paletteBank": 8, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 41, "paletteBank": 9, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 42, "paletteBank": 10, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 43, "paletteBank": 11, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 44, "paletteBank": 12, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 45, "paletteBank": 13, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 46, "paletteBank": 14, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 47, "paletteBank": 15, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 48, "paletteBank": 0, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 49, "paletteBank": 1, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 50, "paletteBank": 2, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 51, "paletteBank": 3, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 52, "paletteBank": 4, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 53, "paletteBank": 5, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 54, "paletteBank": 6, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 55, "paletteBank": 7, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 56, "paletteBank": 8, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 57, "paletteBank": 9, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 58, "paletteBank": 10, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 59, "paletteBank": 11, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 60, "paletteBank": 12, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 61, "paletteBank": 13, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 62, "paletteBank": 14, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 63, "paletteBank": 15, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 64, "paletteBank": 0, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 65, "paletteBank": 1, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 66, "paletteBank": 2, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 67, "paletteBank": 3, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 68, "paletteBank": 4, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 69, "paletteBank": 5, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 70, "paletteBank": 6, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 71, "paletteBank": 7, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 72, "paletteBank": 8, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 73, "paletteBank": 9, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 74, "paletteBank": 10, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 75, "paletteBank": 11, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 76, "paletteBank": 12, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 77, "paletteBank": 13, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 78, "paletteBank": 14, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 79, "paletteBank": 15, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 80, "paletteBank": 0, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 81, "paletteBank": 1, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 82, "paletteBank": 2, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 83, "paletteBank": 3, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 84, "paletteBank": 4, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 85, "paletteBank": 5, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 86, "paletteBank": 6, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 87, "paletteBank": 7, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 88, "paletteBank": 8, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 89, "paletteBank": 9, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 90, "paletteBank": 10, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 91, "paletteBank": 11, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 92, "paletteBank": 12, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 93, "paletteBank": 13, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 94, "paletteBank": 14, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 95, "paletteBank": 15, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 96, "paletteBank": 0, "flipX": false, "flipY": false, "priority": false, "chrAlt": false}, {"tile": 97, "paletteBank": 1, "flipX": false, "flipY": false, "priority": fa
